Repository Azure/typespec-azure, pull requests merged in 2024-11, with the labels that each got.

#1780 Backmerge/release/october 2024 2024 10 31
  packages/typespec-client-generator-core/CHANGELOG.md
  packages/typespec-client-generator-core/package.json
  packages/typespec-client-generator-core/src/decorators.ts
  packages/typespec-client-generator-core/src/example.ts
  packages/typespec-client-generator-core/src/http.ts
  packages/typespec-client-generator-core/src/interfaces.ts
  packages/typespec-client-generator-core/src/internal-utils.ts
  packages/typespec-client-generator-core/src/package.ts
  packages/typespec-client-generator-core/src/public-utils.ts
  packages/typespec-client-generator-core/src/types.ts
  packages/typespec-client-generator-core/test/examples/http-operation-examples.test.ts
  packages/typespec-client-generator-core/test/examples/http-operation-examples/bodyWithEncodedName.json
  packages/typespec-client-generator-core/test/package.test.ts
  packages/typespec-client-generator-core/test/packages/parameters.test.ts
  packages/typespec-client-generator-core/test/packages/spread.test.ts
  packages/typespec-client-generator-core/test/public-utils.test.ts
  packages/typespec-client-generator-core/test/types/model-types.test.ts
  packages/typespec-client-generator-core/test/types/union-types.test.ts
Labels: lib:tcgc

#1789 Add ide label for azure specific ide requests
  .github/policies/issues.triage.generated.yml
  .github/policies/prs.triage.generated.yml
  CONTRIBUTING.md
  eng/config/labels.ts
Labels: eng

#1797 Suppress algolia key for new website
  eng/CredScanSuppression.json
Labels: eng

#1798 Publish astro version
  .github/workflows/website-gh-pages.yml
Labels: eng

#1507 Adding issue template for ARM common-types changes
  .github/ISSUE_TEMPLATE/common-types-request.yml
Labels: eng

#1783 Implement scope negation for TCGC
  .chronus/changes/scope-negation-2024-10-1-10-19-14.md
  packages/typespec-client-generator-core/README.md
  packages/typespec-client-generator-core/generated-defs/Azure.ClientGenerator.Core.ts
  packages/typespec-client-generator-core/lib/decorators.tsp
  packages/typespec-client-generator-core/src/decorators.ts
  packages/typespec-client-generator-core/src/internal-utils.ts
  packages/typespec-client-generator-core/test/decorators.test.ts
  website/src/content/docs/docs/libraries/typespec-client-generator-core/reference/decorators.md
Labels: lib:tcgc

#1865 add test for encoded discriminator name
  packages/typespec-client-generator-core/test/types/model-types.test.ts
Labels: lib:tcgc

#1838 No matching versions found
  .chronus/changes/fix-autorest-version-error-2024-10-14-17-31-30.md
  packages/typespec-autorest/src/emit.ts
  packages/typespec-autorest/src/lib.ts
  packages/typespec-autorest/test/versioning.test.ts
Labels: emitter:autorest

#1885 Backmerge/release/november 2024 2024 11 19
  packages/typespec-client-generator-core/CHANGELOG.md
  packages/typespec-client-generator-core/package.json
  packages/typespec-client-generator-core/src/decorators.ts
  packages/typespec-client-generator-core/src/interfaces.ts
  packages/typespec-client-generator-core/src/internal-utils.ts
  packages/typespec-client-generator-core/src/package.ts
  packages/typespec-client-generator-core/src/public-utils.ts
  packages/typespec-client-generator-core/src/types.ts
  packages/typespec-client-generator-core/test/decorators.test.ts
  packages/typespec-client-generator-core/test/decorators/access.test.ts
  packages/typespec-client-generator-core/test/decorators/override.test.ts
  packages/typespec-client-generator-core/test/decorators/usage.test.ts
  packages/typespec-client-generator-core/test/packages/client.test.ts
  packages/typespec-client-generator-core/test/packages/methods.test.ts
  packages/typespec-client-generator-core/test/packages/responses.test.ts
  packages/typespec-client-generator-core/test/public-utils/is-paged-result-model.test.ts
  packages/typespec-client-generator-core/test/types/model-types.test.ts
Labels: lib:tcgc
