Repository Azure/typespec-azure, pull requests merged in 2024-06, with the labels that each got.

#936 [tcgc] update crossLanguageDefinitionId to correspond to apiview
  .chronus/changes/tsp_clid-2024-5-3-18-13-18.md
  packages/typespec-client-generator-core/src/http.ts
  packages/typespec-client-generator-core/src/interfaces.ts
  packages/typespec-client-generator-core/src/internal-utils.ts
  packages/typespec-client-generator-core/src/package.ts
  packages/typespec-client-generator-core/src/public-utils.ts
  packages/typespec-client-generator-core/src/types.ts
  packages/typespec-client-generator-core/test/decorators.test.ts
  packages/typespec-client-generator-core/test/package.test.ts
  packages/typespec-client-generator-core/test/public-utils.test.ts
  packages/typespec-client-generator-core/test/types.test.ts
Labels: lib:tcgc

#950 remove duplicated types in TCGC
  .chronus/changes/resolve-duplicate-types-2024-5-4-7-33-26.md
  packages/typespec-client-generator-core/src/interfaces.ts
Labels: lib:tcgc

#719 [tcgc] add versioning doc
  cspell.yaml
  docs/howtos/DataPlane Generation - DPG/09versioning.mdx
Labels: docs, lib:tcgc

#1017 break up tests for types into multiple files
  .chronus/changes/break-up-test-cases-2024-5-14-14-29-1.md
  packages/typespec-client-generator-core/test/types.test.ts
  packages/typespec-client-generator-core/test/types/array-types.test.ts
  packages/typespec-client-generator-core/test/types/body-model-property-types.test.ts
  packages/typespec-client-generator-core/test/types/built-in-types.test.ts
  packages/typespec-client-generator-core/test/types/constant-types.test.ts
  packages/typespec-client-generator-core/test/types/date-time-types.test.ts
  packages/typespec-client-generator-core/test/types/duration-type.test.ts
  packages/typespec-client-generator-core/test/types/enum-types.test.ts
  packages/typespec-client-generator-core/test/types/model-types.test.ts
  packages/typespec-client-generator-core/test/types/multipart-types.test.ts
  packages/typespec-client-generator-core/test/types/tuple-types.test.ts
  packages/typespec-client-generator-core/test/types/union-types.test.ts
  packages/typespec-client-generator-core/test/types/utils.ts
Labels: lib:tcgc

#1026 Removed unused macos variables
  eng/pipelines/templates/variables/image.yml
Labels: eng

#1009 add `tspNamespace` to `SdkModelType`, `SdkEnumType`, `SdkEnumValueType` and `SdkUnionType`
  .chronus/changes/add-name-and-namespace-to-model-enum-and-enumvalue-2024-5-14-1-46-55.md
  packages/typespec-client-generator-core/src/interfaces.ts
  packages/typespec-client-generator-core/src/types.ts
  packages/typespec-client-generator-core/test/types/enum-types.test.ts
  packages/typespec-client-generator-core/test/types/model-types.test.ts
Labels: lib:tcgc

#1032 Set armId kind for Azure.Core.armResourceIdentifier
  .chronus/changes/fix-arm-id-2024-5-18-17-30-45.md
  packages/typespec-client-generator-core/src/interfaces.ts
  packages/typespec-client-generator-core/test/types/built-in-types.test.ts
Labels: lib:tcgc

#1050 tcgc, arm, set context.arm for explicit client
  .chronus/changes/tcgc_arm_explicit-client-2024-5-21-15-15-43.md
  packages/typespec-client-generator-core/src/decorators.ts
Labels: lib:tcgc
